name: DropPrevention
version: ${project.version}
main: com.tr.donsuzturk.dropprevention.Main
api-version: 1.16
authors: [ DonsuzTurk ]
description: Oyuncuların altında blok yoksa yere item atabilmelerini engeller.
